### ISSUE TITLE
Download of the Arduino V1.11.5 failed

### ISSUE THREAD

**Issue by dlukele** [julianneswinoga/OATFWGUI#41]
I selected the above mentioned fw and wanted to download it in the OAT Firmware GUI to create a firmware. After pressing the "Download" button, I got red error messages (also see logs attached):
[oat_fw_gui_2024-01-23-22-42-30.log](https://github.com/OpenAstroTech/OATFWGUI/files/14030039/oat_fw_gui_2024-01-23-22-42-30.log)

```
2024-01-23 22:43:38,083:CRITICAL:Exception caught 
2024-01-23 22:43:38,083:CRITICAL:Traceback (most recent call last):
  File "shutil.py", line 815, in move
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\mail\\Downloads\\OATFWGUI_1.0.5-release+b849ae_Windows\\OATFWGUI_1.0.5-release+b849ae_Windows\\OpenAstroTech-OpenAstroTracker-Firmware-d387d8d' -> 'C:\\Users\\mail\\Downloads\\OATFWGUI_1.0.5-release+b849ae_Windows\\OATFWGUI_1.0.5-release+b849ae_Windows\\OATFW'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mail\Downloads\OATFWGUI_1.0.5-release+b849ae_Windows\OATFWGUI_1.0.5-release+b849ae_Windows\OATFWGUI\qt_extensions.py", line 44, in run
    raise e
  File "C:\Users\mail\Downloads\OATFWGUI_1.0.5-release+b849ae_Windows\OATFWGUI_1.0.5-release+b849ae_Windows\OATFWGUI\qt_extensions.py", line 39, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\mail\Downloads\OATFWGUI_1.0.5-release+b849ae_Windows\OATFWGUI_1.0.5-release+b849ae_Windows\OATFWGUI\gui_logic.py", line 196, in download_and_extract_fw
    self.logic_state.fw_dir = extract_fw(zipfile_name)
  File "C:\Users\mail\Downloads\OATFWGUI_1.0.5-release+b849ae_Windows\OATFWGUI_1.0.5-release+b849ae_Windows\OATFWGUI\gui_logic.py", line 85, in extract_fw
    shutil.move(extracted_dir, fw_dir)
  File "shutil.py", line 835, in move
  File "shutil.py", line 434, in copy2
  File "shutil.py", line 254, in copyfile
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\mail\\Downloads\\OATFWGUI_1.0.5-release+b849ae_Windows\\OATFWGUI_1.0.5-release+b849ae_Windows\\OpenAstroTech-OpenAstroTracker-Firmware-d387d8d' 
2024-01-23 22:43:38,083:CRITICAL:
This is a bug! Please click the 'Report a bug' button in the bottom right of the window
and attach the latest log file from the 'logs' directory (C:\Users\mail\Downloads\OATFWGUI_1.0.5-release+b849ae_Windows\OATFWGUI_1.0.5-release+b849ae_Windows\logs) 
```

**Comment by julianneswinoga** [comment]
Thank you so much for the bug report!! :smile: 
This does indeed look like a bug, but a really strange one. Was it reproducible? Or did you try again and it worked?

**Comment by dlukele** [comment]
Yes, I could reproduce it and it seems it only happens when the program was started in admin mode on Windows (which confuses me a bit because I thought I could solve problems by using the admin mode 😀 )
